BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Countries] (
    [countryId] INT NOT NULL IDENTITY(1,1),
    [countryCode] NVARCHAR(1000) NOT NULL,
    [name] NVARCHAR(1000) NOT NULL,
    [keyName] NVARCHAR(1000) NOT NULL,
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [Countries_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    [updatedAt] DATETIME2 NOT NULL,
    CONSTRAINT [Countries_pkey] PRIMARY KEY CLUSTERED ([countryId])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
